<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="5" name="MFAC_Test" tests="12" failures="4" timestamp="14 Oct 2018 23:11:15 GMT" time="42.322" errors="0">
  <testcase name="IssuePin" time="4.509" classname="TestNG.MFAC"/>
  <testcase name="IssuePin" time="5.069" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinValid" time="6.436" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinValid" time="12.469" classname="TestNG.MFAC"/>
  <testcase name="IssuePinVelocity" time="17.199" classname="TestNG.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;5700&amp;quot; and a string containing &amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;)
     but: a string containing &amp;quot;5700&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;c8f1986b-d474-4c20-a01d-12fe0e361d49&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;pinOTP&amp;quot;:&amp;quot;503212&amp;quot;,&amp;quot;pinExpirationDate&amp;quot;:&amp;quot;10/14/2018 11:20 PM GMT&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"c8f1986b-d474-4c20-a01d-12fe0e361d49","output":{"pinOTP":"503212","pinExpirationDate":"10/14/2018 11:20 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC.IssuePinVelocity(MFAC.java:212)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePinVelocity" time="20.078" classname="TestNG.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;5700&amp;quot; and a string containing &amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;)
     but: a string containing &amp;quot;5700&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;7c164721-ae4b-4d37-8f13-e5e7db4b43e3&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;pinOTP&amp;quot;:&amp;quot;809046&amp;quot;,&amp;quot;pinExpirationDate&amp;quot;:&amp;quot;10/14/2018 11:40 PM GMT&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"7c164721-ae4b-4d37-8f13-e5e7db4b43e3","output":{"pinOTP":"809046","pinExpirationDate":"10/14/2018 11:40 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC.IssuePinVelocity(MFAC.java:212)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="VerifyPinNoLongerValid" time="20.218" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="25.125" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinVelocity" time="30.192" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinVelocity" time="30.379" classname="TestNG.MFAC"/>
  <testcase name="AddressVelocity" time="37.33" classname="TestNG.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;DENY&amp;quot; and a string containing &amp;quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&amp;quot;)
     but: a string containing &amp;quot;DENY&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;7c18ea5d-85c6-4020-bd08-494cc266fd86&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;advice&amp;quot;:&amp;quot;ALLOW&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "DENY" and a string containing "Unfortunately, too many failed attempts for registration have occurred. Please try again later.")
     but: a string containing "DENY" was "{"transactionId":"7c18ea5d-85c6-4020-bd08-494cc266fd86","output":{"advice":"ALLOW"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC.AddressVelocity(MFAC.java:177)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="AddressVelocity" time="40.752" classname="TestNG.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;DENY&amp;quot; and a string containing &amp;quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&amp;quot;)
     but: a string containing &amp;quot;DENY&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;b18b9315-eae9-4bb3-9810-5f554a554687&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;advice&amp;quot;:&amp;quot;ALLOW&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "DENY" and a string containing "Unfortunately, too many failed attempts for registration have occurred. Please try again later.")
     but: a string containing "DENY" was "{"transactionId":"b18b9315-eae9-4bb3-9810-5f554a554687","output":{"advice":"ALLOW"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC.AddressVelocity(MFAC.java:177)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="IssuePinExpiration" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- IssuePinExpiration -->
  <testcase name="AdditionalEnrollmentExpiration" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="DetermineLockoutTime" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- DetermineLockoutTime -->
  <testcase name="AdditionalEnrollmentExpirationValidate" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- AdditionalEnrollmentExpirationValidate -->
  <testcase name="IssuePinExpirationValidate" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- IssuePinExpirationValidate -->
</testsuite> <!-- MFAC_Test -->
